### ISSUE TITLE
Red Alert when connecting

### ISSUE THREAD

**Issue by djphil** [kcozens/OpenSimMutelist#1]
When i connecting to my simulator (opensim-0.9.0-1713-g1e3cb82.zip) i recieve a red alert on console about the MuteList Module.

18:13:20 - [LLUDPSERVER]: Client packet handler for dj phil for packet MuteListRequest threw System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à OpenSim.Region.CoreModules.Avatar.InstantMessage.MuteListModule.OnMuteListRequest(IClientAPI client, UInt32 crc) dans d:\opensim\mastergrid\addon-modules\OpenSimMutelist\Modules\MutelistModule\OpenMutelist.cs:ligne 285
   à OpenSim.Region.ClientStack.LindenUDP.LLClientView.HandleMuteListRequest(IClientAPI sender, Packet Pack) dans d:\opensim\mastergrid\OpenSim\Region\ClientStack\Linden\UDP\LLClientView.cs:ligne 11035
   à OpenSim.Region.ClientStack.LindenUDP.LLClientView.ProcessPacketMethod(Packet packet) dans d:\opensim\mastergrid\OpenSim\Region\ClientStack\Linden\UDP\LLClientView.cs:ligne 760
   à OpenSim.Region.ClientStack.LindenUDP.LLClientView.ProcessInPacket(Packet packet) dans d:\opensim\mastergrid\OpenSim\Region\ClientStack\Linden\UDP\LLClientView.cs:ligne 13164
   à OpenSim.Region.ClientStack.LindenUDP.LLUDPServer.ProcessInPacket(IncomingPacket incomingPacket) dans d:\opensim\mastergrid\OpenSim\Region\ClientStack\Linden\UDP\LLUDPServer.cs:ligne 2207

**Comment by kcozens** [comment]
PHP encodes an empty string in XML format as &lt;string/&gt;. In the module code the value for that hashtable entry is null and not an empty string. The result was the throwing of an exception when the module tried to do a .ToString() call on the hashtable value.

commit ddf26c3e2e10b4c38e77d6af4280f55609f0469a
Author: Kevin Cozens <kevin@ve3syb.ca>
Date:   Mon Dec 4 14:03:27 2017 -0500

    Prevent exception message if there is no mutelist for an avatar

**Comment by djphil** [comment]
Fixed in https://github.com/kcozens/OpenSimMutelist/commit/ddf26c3e2e10b4c38e77d6af4280f55609f0469a
Ty!
